/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 om_symbol.glb --transform 
Files: om_symbol.glb [2.85MB] > C:\Users\Deepvarsha\OneDrive\Documents\Projects\Ramayan\frontend\public\models\om_symbol-transformed.glb [252.51KB] (91%)
Author: Mustafa.Dasuki (https://sketchfab.com/Mustafa.Dasuki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/om-symbol-55fc060da99e45b189e9f0b7b6f1be02
Title: Om Symbol
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Om(props) {
  const { nodes, materials } = useGLTF('/models/om_symbol-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_9.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}
